dist: trusty
git:
  depth: false
addons:
  sonarcloud:
    organization: "steckk"
    token:
      secure: "rQEHaNGO2sk6oEVRFtI5oxCIIHUQhUo72KRyb2HlcHMeqiby/6n7fFUSM7FEPXA2lenA4di7phxUNkbrnLLOBqFDDyUHHBREbUTLoGgzPmdse1sH2F8B1ddXQSUzzQ6XVwIZOtBO6MDMd82aq7iAfsI7Fxxfu04oDZWYD+El+Vj1/fKqllpywGVf7LzG+IreeRsUU5AWccLp+qbPneD2wGxmKT+OIDorf+cN/Tf7+H+mGYmepZCjbBVDpfBBjQnwBaqN4rqk/ab0UdUQQr3wj/D8RakRVc21yHN9PwbqKNSGjetc8ChN0rNy/jU75Fhu3sQ+w2TIIlnPscT+wImEDuC4eSg+CYdV8XG9gaE+HRnNTGTbTfsiAwcRf2Q+SmYQ9PT/zdVdbdHe2OFVyG1wx4QMZ5RdIfyK6vCu4VwHaRl2mYhoENQbdzp4VGVOVnXBabeHL68gQff4QeiGjp9KctRhWtfByPz86kWbeEKb0FE5K50uZdAYWqmZEPztRVECKKqmbhWowSOnaKK1uYUTcQtB9ljW1PgQcSJGzYlra+p64q4Ft028lGxkUPsKEZvAXqBhCKldNs2K+EgHVUa7MpbeoJt++m/UBeEcf+NGY+WD4KJPNKgYBXjwZzL7aqvPpURNyD4ie0Oq53HmWhNSVX5kLvUIlepQXh36zFlNrlA="
language: python
python:
- '3.6'
before_install:
  - pip install --upgrade pytest
  - pip install numpy --upgrade
install:
- pip install .[test]
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
script:
- rm -rf .coverage
- coverage erase
- pytest --cov=bioinformatica --cov-report xml:coverage.xml 
- coverage combine --append || true
- coverage report
- coverage xml
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi' # sonar only on non-PRs

after_success:
  - coveralls
  - python-codacy-coverage -r coverage.xml
